{{- if .Values.open-webui.discoverable.allow }}
{{- $fullname := include "library-chart.fullname" . }}
{{- $serviceName:= printf "%s-%s" .Release.Name "open-webui" }}
{{- $secretName := printf "%s-%s" "discoverable" $fullname -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  annotations:
    onyxia/discovery: "elastic"
type: Opaque
data:
{{- if .Values.ingress.enabled }}
  elastic-service: {{ printf "%s" .Values.ingress.hostname | b64enc | quote }}
  elastic-port: {{ "443" | b64enc | quote }}
  elastic-name: {{ printf "%s" $fullname  | b64enc | quote }}
  elastic-schema: {{ "default" | b64enc | quote }}
  elastic-tls: {{ printf "%t" .Values.ingress.tls | b64enc | quote }}
{{- if .Values.open-webui.security.enabled }}
  elastic-password: {{ printf "%s" .Values.open-webui.security.elasticPassword | b64enc | quote}}
  elastic-security: {{ "PASSWORD" | b64enc | quote }}
  elastic-username: {{ "elastic" | b64enc | quote}}
  elastic-ignore-publish-address: {{ "true" | b64enc | quote}}
{{- end -}}
{{- else }}
  elastic-service: {{ printf "%s" $serviceName | b64enc | quote }}
  elastic-port: {{ include "open-webui.service.ports.restAPI" .Subcharts.open-webui | b64enc | quote }}
  elastic-name: {{ printf "%s" $fullname  | b64enc | quote }}
  elastic-tls: {{ printf "%t" .Values.open-webui.security.tls.restEncryption | b64enc | quote }}
{{- if .Values.open-webui.security.enabled }}
  elastic-password: {{ printf "%s" .Values.open-webui.security.elasticPassword | b64enc | quote}}
  elastic-security: {{ printf "%s" "PASSWORD" | b64enc | quote }}
  elastic-username: {{ printf "%s" "elastic" | b64enc | quote}}
  elastic-ignore-publish-address: {{ "true" | b64enc | quote}}
{{- end -}}
{{- end -}}
{{- end -}}