{{- if .Values.route.enabled -}}
{{- $svcPort := .Values.open-webui.service.ports.restAPI  -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-elastic
  labels:
    {{- include "library-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- include "library-chart.route.annotations" . | nindent 4 }}
spec:
  host: {{ .Values.route.hostname | quote }}
  path: /
  to:
    kind: Service
    name:  {{ include "open-webui.service.name" .Subcharts.open-webui }}
  port: 
    targetPort: {{ $svcPort }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    {{- if .Values.route.tls.key }}
    key: {{- .Values.route.tls.key }}
    {{- end }}
    {{- if .Values.route.tls.certificate }}
    certificate: {{- .Values.route.tls.certificate }}
    {{- end }}
    {{- if .Values.route.tls.caCertificate }}
    caCertificate: {{- .Values.route.tls.caCertificate }}
    {{- end }}
    {{- if .Values.route.tls.destinationCACertificate }}
    destinationCACertificate: {{- .Values.route.tls.destinationCACertificate }}
    {{- end }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
{{- end }}